# Generated by Django 5.2.17 on 2026-09-12 08:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("platform_core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="must_change_password",
            field=models.BooleanField(default=False),
        ),
    ]
