# Generated by Django 5.2.17 on 2026-09-12 08:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("platform_core", "0002_user_must_change_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditevent",
            name="details",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="auditevent",
            name="request_id",
            field=models.CharField(blank=True, max_length=36),
        ),
    ]
