# Generated by Django 5.2.17 on 2026-09-12 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("platform_core", "0005_changeplan_chatturn_connector_knowledgeentry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="status",
            field=models.CharField(
                choices=[
                    ("quarantined", "Awaiting security scan"),
                    ("ready", "Ready"),
                    ("rejected", "Rejected by scanner"),
                ],
                default="quarantined",
                max_length=20,
            ),
        ),
    ]
