# Generated by Django 5.2.17 on 2026-09-12 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("platform_core", "0006_alter_document_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="knowledgeentry",
            name="document",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="platform_core.document",
            ),
        ),
        migrations.CreateModel(
            name="AIConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("model", models.CharField(max_length=160)),
                ("enabled", models.BooleanField(default=True)),
                ("input_rate", models.DecimalField(decimal_places=6, max_digits=12)),
                ("output_rate", models.DecimalField(decimal_places=6, max_digits=12)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, to="platform_core.application"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("input_rate__gte", 0), ("output_rate__gte", 0)),
                        name="nonnegative_ai_rates",
                    )
                ],
            },
        ),
    ]
