# Generated by Django 5.2.17 on 2026-09-12 09:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("platform_core", "0007_alter_knowledgeentry_document_aiconfiguration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="status",
            field=models.CharField(
                choices=[
                    ("quarantined", "Uploaded"),
                    ("ready", "Ready"),
                    ("rejected", "Rejected by scanner"),
                ],
                default="quarantined",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="knowledgeentry",
            name="content",
            field=models.TextField(max_length=1000000),
        ),
    ]
