# Generated by Django 5.2.17 on 2026-09-12 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("platform_core", "0008_alter_document_status_alter_knowledgeentry_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="conversion_actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="document_conversions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="conversion_error",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="document",
            name="conversion_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="converter",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name="document",
            name="status",
            field=models.CharField(
                choices=[
                    ("quarantined", "Uploaded"),
                    ("queued", "Queued for conversion"),
                    ("converting", "Converting to Markdown"),
                    ("deleted", "Deleted"),
                    ("ready", "Ready for graph generation"),
                    ("failed", "Conversion failed"),
                    ("rejected", "Rejected by scanner"),
                ],
                default="quarantined",
                max_length=20,
            ),
        ),
    ]
