# Generated by Django 5.2.17 on 2026-09-12 09:37

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("platform_core", "0009_document_conversion_actor_document_conversion_error_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeGraph",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("version", models.UUIDField(default=uuid.uuid4)),
                ("fingerprint", models.CharField(blank=True, max_length=64)),
                ("status", models.CharField(default="building", max_length=16)),
                ("data", models.JSONField(default=dict)),
                ("quality", models.JSONField(default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="platform_core.application"
                    ),
                ),
            ],
        ),
    ]
