# Generated by Django 5.2.17 on 2026-09-12 09:45

import uuid

import django.db.models.deletion
from django.db import migrations, models


def preserve_current_graphs(apps, schema_editor):
    Graph = apps.get_model("platform_core", "KnowledgeGraph")
    Revision = apps.get_model("platform_core", "GraphRevision")
    for graph in (
        Graph.objects.using(schema_editor.connection.alias).filter(status="ready").iterator()
    ):
        revision = Revision.objects.using(schema_editor.connection.alias).create(
            id=graph.version,
            application_id=graph.application_id,
            number=1,
            fingerprint=graph.fingerprint,
            data=graph.data,
            quality=graph.quality,
        )
        Revision.objects.using(schema_editor.connection.alias).filter(pk=revision.pk).update(
            created_at=graph.updated_at
        )


class Migration(migrations.Migration):
    dependencies = [
        ("platform_core", "0010_knowledgegraph"),
    ]

    operations = [
        migrations.CreateModel(
            name="GraphRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                ("fingerprint", models.CharField(max_length=64)),
                ("data", models.JSONField(default=dict)),
                ("quality", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="platform_core.application"
                    ),
                ),
            ],
            options={
                "ordering": ["-number"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("application", "number"), name="unique_graph_revision"
                    )
                ],
            },
        ),
        migrations.RunPython(preserve_current_graphs, migrations.RunPython.noop),
    ]
