# Generated by Django 5.2.17 on 2026-09-12 16:44

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def preserve_history(apps, schema_editor):
    Turn = apps.get_model("platform_core", "ChatTurn")
    Conversation = apps.get_model("platform_core", "ChatConversation")
    db = schema_editor.connection.alias
    pairs = Turn.objects.using(db).order_by().values_list("application_id", "user_id").distinct()
    for app_id, user_id in pairs.iterator():
        turns = Turn.objects.using(db).filter(application_id=app_id, user_id=user_id)
        first = turns.order_by("created_at", "id").first()
        last = turns.order_by("-created_at", "-id").first()
        conversation = Conversation.objects.using(db).create(
            application_id=app_id, user_id=user_id, title="Earlier chat history"
        )
        Conversation.objects.using(db).filter(pk=conversation.pk).update(
            created_at=first.created_at, updated_at=last.created_at
        )
        turns.update(conversation_id=conversation.pk)


class Migration(migrations.Migration):
    dependencies = [
        ("platform_core", "0011_graphrevision"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatturn",
            name="mode",
            field=models.CharField(
                choices=[("search", "Sources"), ("ai", "AI")], default="search", max_length=10
            ),
        ),
        migrations.CreateModel(
            name="ChatConversation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="platform_core.application"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="chatturn",
            name="conversation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="turns",
                to="platform_core.chatconversation",
            ),
        ),
        migrations.RunPython(preserve_history, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="chatturn",
            name="conversation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="turns",
                to="platform_core.chatconversation",
            ),
        ),
        migrations.AddIndex(
            model_name="chatconversation",
            index=models.Index(
                fields=["application", "user", "-updated_at"], name="platform_co_applica_0dcd91_idx"
            ),
        ),
    ]
