# Generated by Django 5.2.17 on 2026-09-12 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("platform_core", "0012_chatturn_mode_chatconversation_chatturn_conversation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aiconfiguration",
            name="configured_by",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="aiconfiguration",
            name="provider",
            field=models.CharField(
                choices=[("openai", "OpenAI Agents SDK"), ("claude", "Claude Agent SDK")],
                default="openai",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="aiconfiguration",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("chat", "Chat conversation"),
                    ("graph_generation", "Graph generation"),
                    ("graph_retrieval", "Graph retrieval"),
                ],
                default="chat",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="aiusage",
            name="purpose",
            field=models.CharField(default="chat", max_length=24),
        ),
        migrations.AlterField(
            model_name="aiconfiguration",
            name="application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="platform_core.application"
            ),
        ),
        migrations.AlterField(
            model_name="chatturn",
            name="mode",
            field=models.CharField(
                choices=[("search", "Sources"), ("ai", "AI"), ("graph", "Graph answer")],
                default="search",
                max_length=10,
            ),
        ),
    ]
