# Generated by Django 5.2.17 on 2026-09-12 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0013_aiconfiguration_configured_by_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='aiconfiguration',
            constraint=models.UniqueConstraint(fields=('application', 'purpose'), name='unique_ai_purpose'),
        ),
    ]
