# Generated by Django 5.2.17 on 2026-09-12 21:33

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def split_turns_into_messages(apps, schema_editor):
    """Expand each question+answer turn into a user message and an assistant message.

    Forward-only for data: the reverse is a no-op, because collapsing messages back
    into turns would lose the status, provider and regeneration history the new
    model records.
    """
    Turn = apps.get_model("platform_core", "ChatTurn")
    Message = apps.get_model("platform_core", "ChatMessage")
    Conversation = apps.get_model("platform_core", "ChatConversation")
    db = schema_editor.connection.alias
    for conversation in Conversation.objects.using(db).order_by("pk").iterator():
        sequence = 0
        modes = {}
        turns = (
            Turn.objects.using(db)
            .filter(conversation_id=conversation.pk)
            .order_by("created_at", "id")
        )
        for turn in turns.iterator():
            ask = Message.objects.using(db).create(
                application_id=turn.application_id,
                user_id=turn.user_id,
                conversation_id=conversation.pk,
                role="user",
                status="complete",
                body=turn.question,
                citations=[],
                mode=turn.mode,
                sequence=sequence,
            )
            reply = Message.objects.using(db).create(
                # Reuse the turn ID so audit events recorded against it still resolve.
                id=turn.id,
                application_id=turn.application_id,
                user_id=turn.user_id,
                conversation_id=conversation.pk,
                role="assistant",
                status="complete",
                body=turn.answer,
                citations=turn.citations,
                mode=turn.mode,
                sequence=sequence + 1,
            )
            # created_at is auto_now_add and cannot be set on create(), even here.
            Message.objects.using(db).filter(pk__in=[ask.pk, reply.pk]).update(
                created_at=turn.created_at, finished_at=turn.created_at
            )
            modes[turn.mode] = modes.get(turn.mode, 0) + 1
            sequence += 2
        if modes:
            Conversation.objects.using(db).filter(pk=conversation.pk).update(
                mode=max(modes, key=modes.get)
            )


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0014_aiconfiguration_unique_ai_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatconversation',
            name='mode',
            field=models.CharField(choices=[('search', 'Sources'), ('ai', 'AI'), ('graph', 'Graph answer')], default='ai', max_length=10),
        ),
        migrations.AddField(
            model_name='chatconversation',
            name='title_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'You'), ('assistant', 'Digital Brain')], max_length=10)),
                ('status', models.CharField(choices=[('streaming', 'Streaming'), ('complete', 'Complete'), ('stopped', 'Stopped'), ('failed', 'Failed')], default='complete', max_length=12)),
                ('body', models.TextField(blank=True, max_length=200000)),
                ('citations', models.JSONField(default=list)),
                ('mode', models.CharField(choices=[('search', 'Sources'), ('ai', 'AI'), ('graph', 'Graph answer')], default='ai', max_length=10)),
                ('provider', models.CharField(blank=True, max_length=16)),
                ('model', models.CharField(blank=True, max_length=160)),
                ('error', models.CharField(blank=True, max_length=300)),
                ('sequence', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='platform_core.application')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='platform_core.chatconversation')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regenerations', to='platform_core.chatmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sequence', 'created_at', 'id'],
                'indexes': [models.Index(fields=['conversation', 'sequence'], name='platform_co_convers_c0c23f_idx')],
                'constraints': [models.UniqueConstraint(fields=('conversation', 'sequence'), name='unique_conversation_sequence')],
            },
        ),
        migrations.RunPython(
            split_turns_into_messages, migrations.RunPython.noop
        ),
    ]
