# Generated by Django 5.2.17 on 2026-09-12 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0015_chatconversation_mode_chatconversation_title_locked_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatTurn',
        ),
    ]
