# Generated by Django 5.2.17 on 2026-09-12 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0016_remove_chatturn'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatconversation',
            name='graph_version',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
