# Generated by Django 5.2.17 on 2026-09-12 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0017_conversation_graph_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiconfiguration',
            name='purpose',
            field=models.CharField(choices=[('chat', 'Chat conversation'), ('graph_generation', 'Graph generation'), ('graph_retrieval', 'Graph retrieval'), ('conversation_title', 'Conversation titles'), ('plan_drafting', 'Code Factory drafting')], default='chat', max_length=24),
        ),
    ]
