# Generated by Django 5.2.17 on 2026-09-12 22:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def publish_current_revisions(apps, schema_editor):
    """Publish whatever each application is already answering from.

    Publishing is a new gate. Applying it retroactively would silently take every
    existing graph out of service, so the revision that is live right now becomes
    the published one and behaviour is unchanged on upgrade.
    """
    Graph = apps.get_model("platform_core", "KnowledgeGraph")
    Revision = apps.get_model("platform_core", "GraphRevision")
    db = schema_editor.connection.alias
    stamp = timezone.now()
    for graph in Graph.objects.using(db).iterator():
        updated = (
            Revision.objects.using(db)
            .filter(application_id=graph.application_id, pk=graph.version, published_at=None)
            .update(published_at=stamp)
        )
        if updated:
            continue
        # No matching snapshot (an older install, or a graph mid-build): fall back to
        # the newest revision so the application is not left with nothing published.
        newest = (
            Revision.objects.using(db)
            .filter(application_id=graph.application_id)
            .order_by("-number")
            .first()
        )
        if newest is not None and newest.published_at is None:
            Revision.objects.using(db).filter(pk=newest.pk).update(published_at=stamp)


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0018_ai_purposes_titles_and_drafting'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphrevision',
            name='model',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='graphrevision',
            name='provider',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='graphrevision',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='graphrevision',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_graphs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='knowledgegraph',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graph_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='knowledgegraph',
            name='requested_model',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='knowledgegraph',
            name='requested_provider',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddIndex(
            model_name='graphrevision',
            index=models.Index(fields=['application', '-published_at'], name='platform_co_applica_34c328_idx'),
        ),
        migrations.RunPython(
            publish_current_revisions, migrations.RunPython.noop
        ),
    ]
