# Generated by Django 5.2.17 on 2026-09-13 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0019_graph_publishing'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='origin',
            field=models.CharField(choices=[('upload', 'Upload'), ('link', 'Link'), ('github', 'GitHub')], default='upload', max_length=10),
        ),
        migrations.AddField(
            model_name='document',
            name='source_url',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('pending', 'Waiting to download'), ('fetching', 'Downloading'), ('quarantined', 'Uploaded'), ('queued', 'Queued for conversion'), ('converting', 'Converting to Markdown'), ('deleted', 'Deleted'), ('ready', 'Ready to search'), ('failed', 'Conversion failed'), ('rejected', 'Rejected by scanner')], default='quarantined', max_length=20),
        ),
    ]
