# Generated by Django 5.2.17 on 2026-09-13 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0020_document_link_sources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='origin',
            field=models.CharField(choices=[('upload', 'Upload'), ('link', 'Link'), ('github', 'GitHub'), ('sharepoint', 'SharePoint')], default='upload', max_length=10),
        ),
    ]
