# Generated by Django 5.2.17 on 2026-09-13 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0022_api_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgegraph',
            name='stage',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='knowledgegraph',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
