# Generated by Django 5.2.17 on 2026-09-13 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0024_chatretention'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgegraph',
            name='failure_reason',
            field=models.TextField(blank=True),
        ),
    ]
