# Generated by Django 5.2.17 on 2026-09-14 04:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def carry_repository_into_config(apps, schema_editor):
    """Move each existing GitHub connector's repository into the new config.

    Without this the column is dropped and every configured connector comes back
    pointing at nothing.
    """
    Connector = apps.get_model("platform_core", "Connector")
    for connector in Connector.objects.all():
        connector.kind = "github"
        connector.config = {"repository": connector.repository}
        connector.name = connector.name or connector.repository or "GitHub issues"
        connector.save(update_fields=["kind", "config", "name"])


def put_repository_back(apps, schema_editor):
    Connector = apps.get_model("platform_core", "Connector")
    for connector in Connector.objects.all():
        connector.repository = (connector.config or {}).get("repository", "")
        connector.save(update_fields=["repository"])


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0025_knowledgegraph_failure_reason'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='connector',
            options={'ordering': ['kind', 'name']},
        ),
        migrations.AddField(
            model_name='connector',
            name='config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='connector',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='connector',
            name='kind',
            field=models.CharField(choices=[('github', 'GitHub issues'), ('jira', 'Jira issues'), ('servicenow', 'ServiceNow records')], default='github', max_length=20),
        ),
        migrations.AddField(
            model_name='connector',
            name='last_duration_ms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='connector',
            name='last_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='connector',
            name='last_status',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='connector',
            name='name',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='connector',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='platform_core.application'),
        ),
        migrations.RunPython(carry_repository_into_config, put_repository_back),
        migrations.RemoveField(
            model_name='connector',
            name='repository',
        ),
        migrations.AddConstraint(
            model_name='connector',
            constraint=models.UniqueConstraint(fields=('application', 'kind', 'name'), name='unique_connector_name'),
        ),
    ]
