# Generated by Django 5.2.17 on 2026-09-14 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0026_connector_kinds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connector',
            name='kind',
            field=models.CharField(choices=[('github', 'GitHub'), ('jira', 'Jira'), ('servicenow', 'ServiceNow')], default='github', max_length=20),
        ),
    ]
