# Generated by Django 5.2.17 on 2026-09-14 09:13

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0027_connector_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeplan',
            name='graph_version',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='FactoryRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticket_external_id', models.CharField(blank=True, max_length=120)),
                ('ticket_title', models.CharField(blank=True, max_length=300)),
                ('ticket_url', models.URLField(blank=True, max_length=1000)),
                ('ticket_digest', models.CharField(blank=True, max_length=64)),
                ('graph_version', models.PositiveIntegerField(blank=True, null=True)),
                ('proposed_repository', models.CharField(blank=True, max_length=200)),
                ('repository_confirmed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Queued'), ('running', 'Running'), ('awaiting_review', 'Awaiting review'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='platform_core.application')),
                ('connector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='platform_core.connector')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='platform_core.changeplan')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PlanItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('stated', 'Stated in the ticket'), ('functional', 'Functional gap'), ('non_functional', 'Non-functional gap')], max_length=16)),
                ('rubric', models.CharField(blank=True, choices=[('security', 'Security and privacy'), ('availability', 'Availability and operability'), ('performance', 'Performance and resource limits'), ('auditability', 'Auditability and correctness')], max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('explanation', models.TextField(max_length=4000)),
                ('change_summary', models.TextField(max_length=4000)),
                ('targets', models.JSONField(blank=True, default=list)),
                ('citations', models.JSONField(blank=True, default=list)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=8)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='proposed', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='platform_core.changeplan')),
            ],
            options={
                'ordering': ['plan', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='RunPhase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('triage', 'Triage'), ('analysis', 'Analysis'), ('design', 'Design'), ('implementation', 'Implementation'), ('verification', 'Verification'), ('delivery', 'Delivery')], max_length=20)),
                ('sequence', models.PositiveIntegerField()),
                ('agent', models.CharField(blank=True, max_length=60)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('ok', 'Succeeded'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=12)),
                ('provider', models.CharField(blank=True, max_length=12)),
                ('model', models.CharField(blank=True, max_length=160)),
                ('prompt_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('completion_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('citations_verified', models.PositiveIntegerField(default=0)),
                ('citations_rejected', models.PositiveIntegerField(default=0)),
                ('input_digest', models.CharField(blank=True, max_length=64)),
                ('output_digest', models.CharField(blank=True, max_length=64)),
                ('output', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='platform_core.factoryrun')),
            ],
            options={
                'ordering': ['run', 'sequence'],
            },
        ),
        migrations.AddIndex(
            model_name='factoryrun',
            index=models.Index(fields=['application', '-created_at'], name='platform_co_applica_6b4c6b_idx'),
        ),
        migrations.AddConstraint(
            model_name='runphase',
            constraint=models.UniqueConstraint(fields=('run', 'name'), name='unique_run_phase'),
        ),
    ]
