# Generated by Django 5.2.17 on 2026-09-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0028_code_factory_runs'),
    ]

    operations = [
        migrations.AddField(
            model_name='factoryrun',
            name='base_branch',
            field=models.CharField(default='main', max_length=200),
        ),
        migrations.AddField(
            model_name='factoryrun',
            name='pull_request_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='factoryrun',
            name='status',
            field=models.CharField(choices=[('pending', 'Queued'), ('running', 'Running'), ('awaiting_review', 'Awaiting review'), ('delivering', 'Delivering'), ('delivered', 'Pull request opened'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
