# Generated by Django 5.2.17 on 2026-09-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0033_code_graph_opt_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='codefile',
            name='cycle_group',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='codefile',
            name='role',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='codesnapshot',
            name='cycle_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='codesnapshot',
            name='orphan_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
