# Generated by Django 5.2.17 on 2026-09-15 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0034_code_graph_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='codefile',
            name='calls',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='codefile',
            name='routes',
            field=models.JSONField(default=list),
        ),
    ]
