# Generated by Django 5.2.17 on 2026-09-17 04:37

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0036_chat_api_opt_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='orphaned',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='KnowledgeSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(default='link', max_length=10)),
                ('url', models.CharField(max_length=2000)),
                ('name', models.CharField(max_length=240)),
                ('status', models.CharField(choices=[('ready', 'In sync'), ('stale', 'Out of sync'), ('unknown', 'Not checked yet'), ('unreachable', 'Could not be checked')], default='unknown', max_length=12)),
                ('fingerprint', models.CharField(blank=True, max_length=120)),
                ('drift_summary', models.CharField(blank=True, max_length=500)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_sources', to='platform_core.application')),
            ],
            options={
                'ordering': ['name', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='platform_core.knowledgesource'),
        ),
        migrations.AddIndex(
            model_name='knowledgesource',
            index=models.Index(fields=['application', 'status'], name='platform_co_applica_ca4b24_idx'),
        ),
        migrations.AddConstraint(
            model_name='knowledgesource',
            constraint=models.UniqueConstraint(fields=('application', 'url'), name='unique_knowledge_source'),
        ),
    ]
