# Generated by Django 5.2.17 on 2026-09-17 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0037_knowledge_sources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connector',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
