# Generated by Django 5.2.17 on 2026-09-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0039_managed_credentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='connector',
            name='last_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='connector',
            name='prune_missing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='connector',
            name='sync_interval_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
