# Generated by Django 5.2.17 on 2026-09-18 03:32

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0040_connector_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField()),
                ('phase', models.CharField(blank=True, max_length=20)),
                ('level', models.CharField(choices=[('step', 'Step'), ('check', 'Check'), ('result', 'Result'), ('problem', 'Problem')], default='step', max_length=8)),
                ('message', models.CharField(max_length=300)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='platform_core.factoryrun')),
            ],
            options={
                'ordering': ['run', 'sequence', 'at'],
                'indexes': [models.Index(fields=['run', 'sequence'], name='platform_co_run_id_4d1806_idx')],
            },
        ),
    ]
