# Generated by Django 5.2.17 on 2026-09-18 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0041_runevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='coderepository',
            name='retired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
