# Generated by Django 5.2.17 on 2026-09-18 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0042_coderepository_retired_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='setup_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
