# Generated by Django 5.2.17 on 2026-09-18 06:01

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0043_application_setup_completed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factoryrun',
            name='status',
            field=models.CharField(choices=[('pending', 'Queued'), ('running', 'Running'), ('awaiting_review', 'Awaiting review'), ('preparing', 'Writing the change'), ('prepared', 'Ready to open a pull request'), ('delivering', 'Opening the pull request'), ('delivered', 'Pull request opened'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='ProposedChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=400)),
                ('content', models.TextField()),
                ('base_sha', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='platform_core.factoryrun')),
            ],
            options={
                'ordering': ['run', 'path'],
                'constraints': [models.UniqueConstraint(fields=('run', 'path'), name='unique_run_change')],
            },
        ),
    ]
