# Generated by Django 5.2.17 on 2026-09-18 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0044_alter_factoryrun_status_proposedchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='factoryrun',
            name='acting_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='factory_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='factoryrun',
            name='status',
            field=models.CharField(choices=[('pending', 'Queued'), ('running', 'Running'), ('awaiting_review', 'Awaiting review'), ('prepare_queued', 'Queued to write the change'), ('preparing', 'Writing the change'), ('prepared', 'Ready to open a pull request'), ('delivering', 'Opening the pull request'), ('delivered', 'Pull request opened'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
