# Generated by Django 5.2.17 on 2026-09-18 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0045_factoryrun_acting_user_alter_factoryrun_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runphase',
            name='name',
            field=models.CharField(choices=[('triage', 'Triage'), ('analysis', 'Analysis'), ('design', 'Design'), ('work_order', 'Work order'), ('implementation', 'Implementation'), ('tests', 'Test author'), ('review', 'Change review'), ('verification', 'Verification'), ('delivery', 'Delivery')], max_length=20),
        ),
    ]
