# Generated by Django 5.2.17 on 2026-09-18 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0046_alter_runphase_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='factoryrun',
            name='branch',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='factoryrun',
            name='checks',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='factoryrun',
            name='checks_read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
