# Generated by Django 5.2.17 on 2026-09-18 07:03

from django.db import migrations, models


def number_existing_runs(apps, schema_editor):
    """Number the runs that already exist, oldest first within each application.

    A default of 0 would collide the moment a second run existed, and the
    constraint added in this migration would refuse it. Numbering them in the
    order they happened also makes the numbers mean what a reader expects.
    """
    FactoryRun = apps.get_model("platform_core", "FactoryRun")
    seen = {}
    for run in FactoryRun.objects.order_by("application_id", "created_at", "id"):
        seen[run.application_id] = seen.get(run.application_id, 0) + 1
        run.number = seen[run.application_id]
        run.save(update_fields=["number"])


def unnumber(apps, schema_editor):
    """Reversing needs nothing: the column goes with it."""


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0047_factoryrun_branch_factoryrun_checks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factoryrun',
            name='number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(number_existing_runs, unnumber),
        migrations.AddConstraint(
            model_name='factoryrun',
            constraint=models.UniqueConstraint(fields=('application', 'number'), name='unique_run_number'),
        ),
    ]
