# Generated by Django 5.2.17 on 2026-09-18 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0048_factoryrun_number_factoryrun_unique_run_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='coderepository',
            name='head_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coderepository',
            name='head_sha',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
