# Generated by Django 5.2.17 on 2026-09-18 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0050_repository_branch_not_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='factoryrun',
            name='refresh_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factoryrun',
            name='refresh_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='factory_refreshes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='factoryrun',
            name='refresh_choice',
            field=models.CharField(blank=True, choices=[('queued', 'Refresh queued'), ('declined', 'Left as they are')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='factoryrun',
            name='refresh_scope',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
