# Generated by Django 5.2.17 on 2026-09-24 17:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("platform_core", "0051_run_refresh_decision"),
    ]

    operations = [
        migrations.AddField(
            model_name="factoryrun",
            name="ticket_body",
            field=models.TextField(blank=True),
        ),
    ]
