# Generated by Django 5.2.17 on 2026-09-24 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0052_factory_run_ticket_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesnapshot',
            name='test_setup',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
