# Generated by Django 5.2.17 on 2026-09-24 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0053_snapshot_test_setup'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesnapshot',
            name='languages',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
