# Generated by Django 5.2.17 on 2026-09-25 10:46

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("platform_core", "0054_snapshot_languages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aiconfiguration",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("chat", "Chat conversation"),
                    ("serviceops_triage", "ServiceOps triage"),
                    ("graph_generation", "Graph generation"),
                    ("graph_retrieval", "Graph retrieval"),
                    ("conversation_title", "Conversation titles"),
                    ("plan_drafting", "Code Factory drafting"),
                ],
                default="chat",
                max_length=24,
            ),
        ),
        migrations.CreateModel(
            name="TriageRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("trigger", models.CharField(default="manual", max_length=12)),
                ("status", models.CharField(default="evidence", max_length=20)),
                ("incident_digest", models.CharField(max_length=64)),
                ("fingerprint", models.CharField(blank=True, max_length=16)),
                ("pack_digest", models.CharField(max_length=64)),
                ("evidence", models.JSONField(default=list)),
                ("band", models.CharField(default="insufficient", max_length=20)),
                ("score_components", models.JSONField(default=dict)),
                ("limitations", models.JSONField(default=list)),
                ("provider", models.CharField(blank=True, max_length=20)),
                ("model", models.CharField(blank=True, max_length=160)),
                ("prompt_version", models.CharField(default="v1", max_length=20)),
                ("scorer_version", models.CharField(default="v1", max_length=20)),
                ("error", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="platform_core.application"
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="platform_core.knowledgeentry",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TriageHypothesis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("rank", models.PositiveSmallIntegerField()),
                ("statement", models.CharField(max_length=600)),
                ("next_step", models.CharField(max_length=600)),
                ("citations", models.JSONField(default=list)),
                ("counter_evidence", models.CharField(blank=True, max_length=600)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hypotheses",
                        to="platform_core.triagerun",
                    ),
                ),
            ],
            options={
                "ordering": ["rank"],
            },
        ),
        migrations.CreateModel(
            name="TriageVerdict",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "verdict",
                    models.CharField(
                        choices=[
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("partial", "Partial"),
                        ],
                        max_length=12,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=1000)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actual_cause",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="platform_core.knowledgeentry",
                    ),
                ),
                (
                    "hypothesis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verdicts",
                        to="platform_core.triagehypothesis",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IncidentProfile",
            fields=[
                (
                    "entry",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="platform_core.knowledgeentry",
                    ),
                ),
                ("source_digest", models.CharField(max_length=64)),
                ("number", models.CharField(blank=True, max_length=80)),
                ("service", models.CharField(blank=True, max_length=500)),
                ("ci", models.CharField(blank=True, max_length=500)),
                ("priority", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("fingerprint", models.CharField(blank=True, max_length=16)),
                ("terms", models.JSONField(default=list)),
                ("opened_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="platform_core.application"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["application", "service", "resolved_at"],
                        name="platform_co_applica_95c724_idx",
                    ),
                    models.Index(
                        fields=["application", "fingerprint"], name="platform_co_applica_9386e5_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="triagerun",
            index=models.Index(
                fields=["application", "incident", "created_at"],
                name="platform_co_applica_167d3f_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="triagehypothesis",
            constraint=models.UniqueConstraint(fields=("run", "rank"), name="unique_triage_rank"),
        ),
    ]
