# Generated by Django 5.2.17 on 2026-09-26 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0055_alter_aiconfiguration_purpose_triagerun_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconfiguration',
            name='output_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aiconfiguration',
            name='purpose',
            field=models.CharField(choices=[('chat', 'Chat conversation'), ('plan_drafting', 'Code Factory'), ('serviceops_triage', 'ServiceOps'), ('graph_generation', 'Graph generation'), ('graph_retrieval', 'Graph retrieval'), ('conversation_title', 'Conversation titles')], default='chat', max_length=24),
        ),
    ]
