# Generated by Django 5.2.17 on 2026-09-26 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0057_enable_serviceops_ai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='origin',
            field=models.CharField(choices=[('upload', 'Upload'), ('link', 'Link'), ('github', 'GitHub'), ('sharepoint', 'SharePoint'), ('folder', 'Folder')], default='upload', max_length=10),
        ),
        migrations.AlterField(
            model_name='knowledgesource',
            name='status',
            field=models.CharField(choices=[('ready', 'In sync'), ('stale', 'Out of sync'), ('unknown', 'Not checked yet'), ('unreachable', 'Could not be checked'), ('uploaded', 'Uploaded')], default='unknown', max_length=12),
        ),
    ]
