# Generated by Django 5.2.17 on 2026-09-26 09:22

from django.db import migrations, models


def number_existing(apps, schema_editor):
    """Give runs that predate numbering 1, 2, 3... per application, oldest first."""
    TriageRun = apps.get_model("platform_core", "TriageRun")
    counters = {}
    for run in TriageRun.objects.order_by("created_at", "id"):
        counters[run.application_id] = counters.get(run.application_id, 0) + 1
        TriageRun.objects.filter(pk=run.pk).update(number=counters[run.application_id])


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0058_folder_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='triagerun',
            name='number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='triagerun',
            name='phases',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(number_existing, migrations.RunPython.noop),
    ]
