# Generated by Django 5.2.17 on 2026-09-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0059_triage_run_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='triagehypothesis',
            name='title',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
