# Generated by Django 5.2.17 on 2026-09-26 10:55

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("platform_core", "0060_triage_hypothesis_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="OperationsGraph",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("fingerprint", models.CharField(blank=True, max_length=64)),
                ("built_at", models.DateTimeField(blank=True, null=True)),
                ("node_count", models.PositiveIntegerField(default=0)),
                ("edge_count", models.PositiveIntegerField(default=0)),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operations_graph",
                        to="platform_core.application",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OpsNode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("incident", "Incident"),
                            ("change", "Change"),
                            ("service", "Service"),
                            ("component", "Component"),
                            ("symptom", "Symptom"),
                            ("group", "Assignment group"),
                            ("passage", "Document passage"),
                        ],
                        max_length=12,
                    ),
                ),
                ("key", models.CharField(max_length=300)),
                ("label", models.CharField(max_length=300)),
                ("data", models.JSONField(blank=True, default=dict)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="platform_core.application"
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ops_nodes",
                        to="platform_core.knowledgeentry",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OpsEdge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "relation",
                    models.CharField(
                        choices=[
                            ("on", "is on component"),
                            ("in", "is in service"),
                            ("assigned", "is assigned to"),
                            ("symptom", "has symptom"),
                            ("before", "started before"),
                            ("similar", "is similar to"),
                            ("duplicate", "may be the same event as"),
                            ("mentions", "mentions"),
                            ("confirmed", "was confirmed caused by"),
                        ],
                        max_length=12,
                    ),
                ),
                ("weight", models.FloatField(default=0)),
                ("detail", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="platform_core.application"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verdict",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edges",
                        to="platform_core.triageverdict",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing",
                        to="platform_core.opsnode",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming",
                        to="platform_core.opsnode",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="opsnode",
            index=models.Index(
                fields=["application", "kind"], name="platform_co_applica_1e9aa4_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="opsnode",
            constraint=models.UniqueConstraint(
                fields=("application", "key"), name="unique_ops_node"
            ),
        ),
        migrations.AddIndex(
            model_name="opsedge",
            index=models.Index(
                fields=["application", "relation"], name="platform_co_applica_00439f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="opsedge",
            constraint=models.UniqueConstraint(
                fields=("source", "target", "relation"), name="unique_ops_edge"
            ),
        ),
    ]
