# Generated by Django 5.2.17 on 2026-09-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("platform_core", "0061_operations_graph"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="submission",
            field=models.CharField(blank=True, max_length=36),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["application", "user", "submission"], name="platform_co_applica_d3a69e_idx"
            ),
        ),
    ]
