# Generated by Django 5.2.17 on 2026-09-27 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0063_chat_submission_claim'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationLogo',
            fields=[
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='custom_logo', serialize=False, to='platform_core.application')),
                ('png', models.BinaryField()),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='identity_icon',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='application',
            name='logo_digest',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
