# Generated by Django 5.2.17 on 2026-10-01 10:23

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0064_applicationlogo_application_identity_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connector',
            name='kind',
            field=models.CharField(choices=[('github', 'GitHub'), ('jira', 'Jira'), ('servicenow', 'ServiceNow'), ('awx', 'Ansible AWX'), ('rundeck', 'Rundeck'), ('azure_automation', 'Azure Automation'), ('automation_list', 'Automation list')], default='github', max_length=20),
        ),
        migrations.AlterField(
            model_name='opsedge',
            name='relation',
            field=models.CharField(choices=[('on', 'is on component'), ('in', 'is in service'), ('assigned', 'is assigned to'), ('symptom', 'has symptom'), ('before', 'started before'), ('similar', 'is similar to'), ('duplicate', 'may be the same event as'), ('mentions', 'mentions'), ('confirmed', 'was confirmed caused by'), ('covers', 'is covered by article'), ('cites', 'cites article'), ('targets', 'is targeted by automation'), ('remediates', 'is remediated by automation'), ('references', 'references automation'), ('resolved_by', 'was resolved by automation')], max_length=12),
        ),
        migrations.AlterField(
            model_name='opsnode',
            name='kind',
            field=models.CharField(choices=[('incident', 'Incident'), ('change', 'Change'), ('service', 'Service'), ('component', 'Component'), ('symptom', 'Symptom'), ('group', 'Assignment group'), ('passage', 'Document passage'), ('kb', 'Knowledge article'), ('automation', 'Automation')], max_length=12),
        ),
        migrations.CreateModel(
            name='AutomationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('simulated', 'Simulated')], default='simulated', max_length=12)),
                ('platform', models.CharField(blank=True, max_length=80)),
                ('request', models.JSONField(blank=True, default=dict)),
                ('outcome', models.CharField(blank=True, max_length=600)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platform_core.application')),
                ('automation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='automation_runs', to='platform_core.knowledgeentry')),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incident_automation_runs', to='platform_core.knowledgeentry')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['application', 'incident', 'created_at'], name='platform_co_applica_9b4e36_idx')],
            },
        ),
    ]
