# Generated by Django 5.2.17 on 2026-10-02 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0065_serviceops_kb_and_automations'),
    ]

    operations = [
        migrations.AddField(
            model_name='factoryrun',
            name='delivered_to',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
